export const CREATE_COURSE = 'CREATE_COURSE';
export const INCREMENT_COUNT = 'INCREMENT_COUNT';
export const INCREMENT_COUNT_ASYNC = 'INCREMENT_COUNT_ASYNC';

// POSTS
export const POSTS_FETCH_ASYNC = 'POSTS_FETCH_ASYNC';
export const POSTS_FETCH_SUCCEEDED = 'POSTS_FETCH_SUCCEEDED';
export const POSTS_FETCH_FAILED = 'POSTS_FETCH_FAILED';