export const INCREMENT_COUNT = 'INCREMENT_COUNT';
export const INCREMENT_COUNT_ASYNC = 'INCREMENT_COUNT_ASYNC';

export const ADD_VEHICLE = 'ADD_VEHICLE';
export const VEHICLES_FETCH_SUCCESS = 'VEHICLES_FETCH_SUCCESS';
export const VEHICLES_FETCH_FAIL = 'VEHICLES_FETCH_FAIL';
export const VEHICLES_FETCH_ASYNC = 'VEHICLES_FETCH_ASYNC';